version: 2.1

orbs:
  python:
    executors:
      python:
        docker:
          - image: circleci/python:3.10.6
    commands:
      install-deps:
        steps:
          - run:
              name: Install dependencies
              command: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      execute:
        steps:
          - run:
              name: Execute
              command: |
                pytest

jobs:
  build:
    executor: python/python
    steps:
      - checkout
      - python/install-deps
      - python/execute
  